### ISSUE TITLE
RangeError when running model_converter.js

### ISSUE THREAD

**Issue by justinmgarrigus** [suXinjke/VengeanceRipper#1]
After creating the extract folder from GAME.RSC without a problem, running model_converter.js on the resulting folder yields a RangeError. Below is the error: 

C:\Users\Justin\Downloads\VengeanceRipper-master\VengeanceRipper-master>node model_converter.js C:\Users\Justin\Downloads\VengeanceRipper-master\VengeanceRipper-master\Desktop Output
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 4304. Received 168626721
    at boundsError (internal/buffer.js:77:9)
    at Buffer.readInt32LE (internal/buffer.js:381:5)
    at parseModel (C:\Users\Justin\Downloads\VengeanceRipper-master\VengeanceRipper-master\model_converter.js:118:35)
    at C:\Users\Justin\Downloads\VengeanceRipper-master\VengeanceRipper-master\model_converter.js:183:22
    at Array.map (<anonymous>)
    at main (C:\Users\Justin\Downloads\VengeanceRipper-master\VengeanceRipper-master\model_converter.js:182:32)
    at async C:\Users\Justin\Downloads\VengeanceRipper-master\VengeanceRipper-master\model_converter.js:359:9

**Comment by suXinjke** [comment]
Such error usually happens when it tries to convert a model file that isn't really a model, you say you pointed it at the whole extracted GAME.RSC, when you're supposed to point it at folder only with .BND files.

I could make a failsafe/ignore files but it's not exactly worth it for such niche tool.
